modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Roofs-Compat/issues"

[[mods]]
modId="macawsroofsbyg"
version="1.19.2-1.0"
displayName="Macaw's Roofs - BYG"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-oh-the-biomes-youll-go"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"
displayTest="MATCH_VERSION"
description='''
Compatibility between Macaw's Roofs and Oh The Biomes You'll Go for Minecraft 1.19.2 !
'''
[[dependencies.macawsroofsbyg]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsroofsbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsroofsbyg]]
    modId = "mcwroofs"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.macawsroofsbyg]]
    modId = "byg"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.macawsroofsbyg]]
    modId = "terrablender"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"