package fr.samlegamer.macawsroofsbop;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import fr.samlegamer.macawsroofsbop.block.MRBOPBlocksRegistry;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.kikoz.mcwroofs.MacawsRoofs;

public class MacawsRoofsBOP implements ModInitializer
{
	public static final String MODID = "macawsroofsbop";
	private static final Logger LOGGER = LogManager.getLogger();
	
	@Override
	public void onInitialize()
	{
    	LOGGER.info("Macaw's Roofs - Biomes O Plenty... Loading...");
		MRBOPBlocksRegistry.registry();
		ItemGroupEvents.modifyEntriesEvent(MacawsRoofs.ROOFGROUP).register(content -> {
			content.add(MRBOPBlocksRegistry.dead_roof);
			content.add(MRBOPBlocksRegistry.dead_attic_roof);
			content.add(MRBOPBlocksRegistry.dead_top_roof);
			content.add(MRBOPBlocksRegistry.dead_lower_roof);
			content.add(MRBOPBlocksRegistry.dead_steep_roof);
			content.add(MRBOPBlocksRegistry.dead_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.dead_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_top_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.dead_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.fir_roof);
			content.add(MRBOPBlocksRegistry.fir_attic_roof);
			content.add(MRBOPBlocksRegistry.fir_top_roof);
			content.add(MRBOPBlocksRegistry.fir_lower_roof);
			content.add(MRBOPBlocksRegistry.fir_steep_roof);
			content.add(MRBOPBlocksRegistry.fir_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.fir_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_top_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.fir_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.hellbark_roof);
			content.add(MRBOPBlocksRegistry.hellbark_attic_roof);
			content.add(MRBOPBlocksRegistry.hellbark_top_roof);
			content.add(MRBOPBlocksRegistry.hellbark_lower_roof);
			content.add(MRBOPBlocksRegistry.hellbark_steep_roof);
			content.add(MRBOPBlocksRegistry.hellbark_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.hellbark_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_top_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.hellbark_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_attic_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_top_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_lower_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_steep_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_top_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.jacaranda_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.magic_roof);
			content.add(MRBOPBlocksRegistry.magic_attic_roof);
			content.add(MRBOPBlocksRegistry.magic_top_roof);
			content.add(MRBOPBlocksRegistry.magic_lower_roof);
			content.add(MRBOPBlocksRegistry.magic_steep_roof);
			content.add(MRBOPBlocksRegistry.magic_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.magic_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_top_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.magic_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.mahogany_roof);
			content.add(MRBOPBlocksRegistry.mahogany_attic_roof);
			content.add(MRBOPBlocksRegistry.mahogany_top_roof);
			content.add(MRBOPBlocksRegistry.mahogany_lower_roof);
			content.add(MRBOPBlocksRegistry.mahogany_steep_roof);
			content.add(MRBOPBlocksRegistry.mahogany_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.mahogany_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_top_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.mahogany_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.palm_roof);
			content.add(MRBOPBlocksRegistry.palm_attic_roof);
			content.add(MRBOPBlocksRegistry.palm_top_roof);
			content.add(MRBOPBlocksRegistry.palm_lower_roof);
			content.add(MRBOPBlocksRegistry.palm_steep_roof);
			content.add(MRBOPBlocksRegistry.palm_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.palm_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_top_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.palm_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.redwood_roof);
			content.add(MRBOPBlocksRegistry.redwood_attic_roof);
			content.add(MRBOPBlocksRegistry.redwood_top_roof);
			content.add(MRBOPBlocksRegistry.redwood_lower_roof);
			content.add(MRBOPBlocksRegistry.redwood_steep_roof);
			content.add(MRBOPBlocksRegistry.redwood_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.redwood_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_top_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.redwood_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.umbran_roof);
			content.add(MRBOPBlocksRegistry.umbran_attic_roof);
			content.add(MRBOPBlocksRegistry.umbran_top_roof);
			content.add(MRBOPBlocksRegistry.umbran_lower_roof);
			content.add(MRBOPBlocksRegistry.umbran_steep_roof);
			content.add(MRBOPBlocksRegistry.umbran_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.umbran_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_top_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.umbran_planks_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.willow_roof);
			content.add(MRBOPBlocksRegistry.willow_attic_roof);
			content.add(MRBOPBlocksRegistry.willow_top_roof);
			content.add(MRBOPBlocksRegistry.willow_lower_roof);
			content.add(MRBOPBlocksRegistry.willow_steep_roof);
			content.add(MRBOPBlocksRegistry.willow_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.willow_upper_steep_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_attic_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_top_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_lower_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_steep_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_upper_lower_roof);
			content.add(MRBOPBlocksRegistry.willow_planks_upper_steep_roof);

		});
    	LOGGER.info("Macaw's Roofs - Biomes O Plenty... Finish...");
	}
}