modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Roofs-Compat/issues"

[[mods]]
modId="macawsroofsbop"
version="1.19-1.6"
displayName="Macaw's Roofs - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-biomes-o-plenty"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"
displayTest="MATCH_VERSION"
description='''
Compatibility between Macaw's Roofs and Biome O' Plenty for Minecraft 1.19 !
'''
[[dependencies.macawsroofsbop]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsroofsbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsroofsbop]]
    modId = "mcwroofs"
    mandatory = false
    ordering = "NONE"
    versionRange = "NONE"

[[dependencies.macawsroofsbop]]
    modId = "biomesoplenty"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.macawsroofsbop]]
    modId = "terrablender"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"